<script src="<?= base_url('assets/admin/js/bootstrap.bundle.min.js') ?>"></script>
<script src="<?= base_url('assets/admin/js/Chart.min.js') ?>"></script>
<script src="<?= base_url('assets/admin/js/dynamic-pie-chart.js') ?>"></script>
<script src="<?= base_url('assets/admin/js/moment.min.js') ?>"></script>
<script src="<?= base_url('assets/admin/js/fullcalendar.js') ?>"></script>
<script src="<?= base_url('assets/admin/js/jvectormap.min.js') ?>"></script>
<script src="<?= base_url('assets/admin/js/world-merc.js') ?>"></script>
<script src="<?= base_url('assets/admin/js/polyfill.js') ?>"></script>
<script src="<?= base_url('assets/admin/js/main.js') ?>"></script>